networks:
  kubeorchestra-net:
    driver: bridge
    name: kubeorchestra-network

services:
  mongodb:
    image: mongo:8.0@sha256:02a0cc7939f5ed38f30f9bc714ef5f682d49baf9350c54acf302ce833087fe8a
    container_name: kubeorchestra-mongodb
    restart: unless-stopped
    networks:
      - kubeorchestra-net
    environment:
      MONGO_INITDB_DATABASE: kubeorchestra
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  core:
    image: ghcr.io/kubeorch/core:v0.0.3@sha256:eafafc2187bda39981bc9ae2fe5f80b77d00d26550b985e8a86c184fc8d4452e
    container_name: kubeorchestra-core
    restart: unless-stopped
    networks:
      - kubeorchestra-net
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      KUBEORCH_MONGO_URI: mongodb://mongodb:27017/kubeorchestra
    depends_on:
      mongodb:
        condition: service_healthy

  ui:
    image: ghcr.io/kubeorch/ui:v0.0.3@sha256:7ae131ccca459c582bfa14287bd53e1c74bd79f3b3015560ab6c45d8686839f3
    container_name: kubeorchestra-ui
    restart: unless-stopped
    networks:
      - kubeorchestra-net
    ports:
      - "3001:3000"
    expose:
      - "3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000/v1/api
    depends_on:
      - core

volumes:
  mongodb_data:
    name: kubeorchestra_mongodb_data
  mongodb_config:
    name: kubeorchestra_mongodb_config
